apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  enableAdminAPI: false
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: ebs-sc
        resources:
          requests:
            storage: 50Gi
