apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: grafana-certificate
  namespace: grafana
spec:
  commonName: grafana.myorg.com
  dnsNames:
  - grafana.myorg.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: grafana-acme-certificate
