apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-process-exporter
  labels:
    app: prometheus-process-exporter
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: metrics
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    port: metrics
    path: /metrics
    scheme: http
  selector:
    matchLabels:
      app: prometheus-process-exporter
